import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ─────────────────────────────────────────────────────────────
//  TRANSLATIONS
// ─────────────────────────────────────────────────────────────
const Map<String, Map<String, String>> kTranslations = {
  'en': {
    'app_name':       'PDF Master Pro',
    'tagline':        'The Ultimate PDF Toolkit',
    'get_started':    'Get Started',
    'home':           'Home',
    'tools':          'Tools',
    'history':        'History',
    'settings':       'Settings',
    'choose_file':    'Choose PDF File',
    'no_file':        'No file selected',
    'drag_drop':      'Tap to select a PDF file',
    'or':             'or',
    'merge':          'Merge PDF',
    'merge_desc':     'Combine multiple PDFs into one file',
    'split':          'Split PDF',
    'split_desc':     'Divide PDF into separate files',
    'compress':       'Compress PDF',
    'compress_desc':  'Reduce file size smartly',
    'watermark':      'Watermark',
    'watermark_desc': 'Add text or image watermark',
    'protect':        'Protect PDF',
    'protect_desc':   'Encrypt with password',
    'unlock':         'Unlock PDF',
    'unlock_desc':    'Remove password protection',
    'rotate':         'Rotate Pages',
    'rotate_desc':    'Rotate pages freely',
    'extract':        'Extract Text',
    'extract_desc':   'Pull all text from PDF',
    'info':           'File Info',
    'info_desc':      'View metadata & details',
    'convert':        'Convert PDF',
    'convert_desc':   'PDF to Word / Images / Excel',
    'sign':           'Sign PDF',
    'sign_desc':      'Add digital signature',
    'ocr':            'OCR Scan',
    'ocr_desc':       'Scan & make searchable',
    'organize':       'Organize Pages',
    'organize_desc':  'Reorder & delete pages',
    'language':       'Language',
    'select_lang':    'Select Language',
    'theme':          'Theme',
    'dark':           'Dark Mode',
    'light':          'Light Mode',
    'auto_save':      'Auto-save output files',
    'notifications':  'Notifications',
    'privacy':        '100% Private – files never leave your device',
    'free':           'Free & Unlimited',
    'fast':           'Lightning Fast',
    'secure':         'Bank-level Security',
    'version':        'Version 1.0.0',
    'made_with':      'Made with ❤️ using Flutter',
    'process':        'Process File',
    'done':           'Done! ✓',
    'processing':     'Processing…',
    'cancel':         'Cancel',
    'close':          'Close',
    'success':        'Success!',
    'file_saved':     'File saved to Downloads',
    'file_processed': 'Your file has been processed successfully.',
    'all_tools':      'All Tools',
    'recent':         'Recent Files',
    'search_tools':   'Search tools…',
    'no_recent':      'No recent files yet',
    'ok':             'OK',
    'enter_text':     'Enter watermark text…',
    'enter_pass':     'Enter password…',
    'confirm_pass':   'Confirm password…',
    'select_pages':   'e.g. 1, 3, 5-8',
    'from_page':      'From page',
    'to_page':        'To page',
    'all_pages':      'All Pages',
    'compress_low':   'Low – Best Quality',
    'compress_mid':   'Medium – Balanced',
    'compress_high':  'High – Smallest Size',
    'about':          'About',
    'help':           'Help & Support',
    'rate':           'Rate the App',
    'share_app':      'Share App',
    'pages':          'pages',
    'size':           'Size',
    'author':         'Author',
    'created':        'Created',
    'modified':       'Modified',
    'tap_select':     'Tap here to select your PDF file',
    'popular':        'Popular',
    'new_tag':        'New',
  },
  'ar': {
    'app_name':       'PDF ماستر برو',
    'tagline':        'أقوى أداة لملفات PDF',
    'get_started':    'ابدأ الآن',
    'home':           'الرئيسية',
    'tools':          'الأدوات',
    'history':        'السجل',
    'settings':       'الإعدادات',
    'choose_file':    'اختر ملف PDF',
    'no_file':        'لم يتم اختيار ملف',
    'drag_drop':      'اضغط لاختيار ملف PDF',
    'or':             'أو',
    'merge':          'دمج PDF',
    'merge_desc':     'ادمج عدة ملفات في ملف واحد',
    'split':          'تقسيم PDF',
    'split_desc':     'قسّم الملف إلى ملفات منفصلة',
    'compress':       'ضغط PDF',
    'compress_desc':  'قلّل حجم الملف بذكاء',
    'watermark':      'علامة مائية',
    'watermark_desc': 'أضف نص أو صورة كعلامة مائية',
    'protect':        'حماية PDF',
    'protect_desc':   'تشفير بكلمة مرور',
    'unlock':         'فتح PDF',
    'unlock_desc':    'إزالة كلمة المرور',
    'rotate':         'تدوير الصفحات',
    'rotate_desc':    'دوّر أي صفحة بحرية',
    'extract':        'استخراج النص',
    'extract_desc':   'استخرج كل النص من PDF',
    'info':           'معلومات الملف',
    'info_desc':      'عرض البيانات والتفاصيل',
    'convert':        'تحويل PDF',
    'convert_desc':   'PDF إلى Word أو صور أو Excel',
    'sign':           'توقيع PDF',
    'sign_desc':      'إضافة توقيع رقمي',
    'ocr':            'مسح ضوئي',
    'ocr_desc':       'مسح وجعله قابلاً للبحث',
    'organize':       'تنظيم الصفحات',
    'organize_desc':  'إعادة ترتيب وحذف الصفحات',
    'language':       'اللغة',
    'select_lang':    'اختر اللغة',
    'theme':          'المظهر',
    'dark':           'الوضع الداكن',
    'light':          'الوضع الفاتح',
    'auto_save':      'حفظ تلقائي للملفات',
    'notifications':  'الإشعارات',
    'privacy':        '١٠٠٪ خصوصية – ملفاتك لا تغادر جهازك',
    'free':           'مجاني وبلا حدود',
    'fast':           'سريع جداً',
    'secure':         'أمان عالي المستوى',
    'version':        'الإصدار ١.٠.٠',
    'made_with':      'صُنع بـ ❤️ باستخدام Flutter',
    'process':        'معالجة الملف',
    'done':           'تم! ✓',
    'processing':     'جارٍ المعالجة…',
    'cancel':         'إلغاء',
    'close':          'إغلاق',
    'success':        'نجاح!',
    'file_saved':     'تم حفظ الملف في التنزيلات',
    'file_processed': 'تمت معالجة ملفك بنجاح.',
    'all_tools':      'جميع الأدوات',
    'recent':         'الملفات الأخيرة',
    'search_tools':   'ابحث عن أداة…',
    'no_recent':      'لا توجد ملفات أخيرة',
    'ok':             'موافق',
    'enter_text':     'أدخل نص العلامة المائية…',
    'enter_pass':     'أدخل كلمة المرور…',
    'confirm_pass':   'تأكيد كلمة المرور…',
    'select_pages':   'مثال: ١، ٣، ٥-٨',
    'from_page':      'من صفحة',
    'to_page':        'إلى صفحة',
    'all_pages':      'جميع الصفحات',
    'compress_low':   'خفيف – جودة عالية',
    'compress_mid':   'متوسط – متوازن',
    'compress_high':  'قوي – أصغر حجم',
    'about':          'حول التطبيق',
    'help':           'المساعدة والدعم',
    'rate':           'قيّم التطبيق',
    'share_app':      'مشاركة التطبيق',
    'pages':          'صفحة',
    'size':           'الحجم',
    'author':         'المؤلف',
    'created':        'تاريخ الإنشاء',
    'modified':       'آخر تعديل',
    'tap_select':     'اضغط هنا لاختيار ملف PDF',
    'popular':        'شائع',
    'new_tag':        'جديد',
  },
  'fr': {
    'app_name':       'PDF Master Pro',
    'tagline':        'La boîte à outils PDF ultime',
    'get_started':    'Commencer',
    'home':           'Accueil',
    'tools':          'Outils',
    'history':        'Historique',
    'settings':       'Paramètres',
    'choose_file':    'Choisir un fichier PDF',
    'no_file':        'Aucun fichier sélectionné',
    'drag_drop':      'Appuyer pour sélectionner un PDF',
    'or':             'ou',
    'merge':          'Fusionner PDF',
    'merge_desc':     'Combiner plusieurs PDFs en un',
    'split':          'Diviser PDF',
    'split_desc':     'Diviser le PDF en fichiers séparés',
    'compress':       'Compresser PDF',
    'compress_desc':  'Réduire la taille du fichier',
    'watermark':      'Filigrane',
    'watermark_desc': 'Ajouter un filigrane texte ou image',
    'protect':        'Protéger PDF',
    'protect_desc':   'Chiffrer avec un mot de passe',
    'unlock':         'Déverrouiller PDF',
    'unlock_desc':    'Supprimer la protection par mot de passe',
    'rotate':         'Rotation des pages',
    'rotate_desc':    'Faire pivoter les pages librement',
    'extract':        'Extraire le texte',
    'extract_desc':   'Extraire tout le texte du PDF',
    'info':           'Infos du fichier',
    'info_desc':      'Voir les métadonnées et détails',
    'convert':        'Convertir PDF',
    'convert_desc':   'PDF en Word / Images / Excel',
    'sign':           'Signer PDF',
    'sign_desc':      'Ajouter une signature numérique',
    'ocr':            'Scan OCR',
    'ocr_desc':       'Scanner et rendre consultable',
    'organize':       'Organiser les pages',
    'organize_desc':  'Réordonner et supprimer des pages',
    'language':       'Langue',
    'select_lang':    'Sélectionner la langue',
    'theme':          'Thème',
    'dark':           'Mode sombre',
    'light':          'Mode clair',
    'auto_save':      'Sauvegarde automatique',
    'notifications':  'Notifications',
    'privacy':        '100% Privé – fichiers jamais partagés',
    'free':           'Gratuit & Illimité',
    'fast':           'Ultra Rapide',
    'secure':         'Sécurité bancaire',
    'version':        'Version 1.0.0',
    'made_with':      'Fait avec ❤️ en Flutter',
    'process':        'Traiter le fichier',
    'done':           'Terminé! ✓',
    'processing':     'Traitement…',
    'cancel':         'Annuler',
    'close':          'Fermer',
    'success':        'Succès!',
    'file_saved':     'Fichier sauvegardé dans Téléchargements',
    'file_processed': 'Votre fichier a été traité avec succès.',
    'all_tools':      'Tous les outils',
    'recent':         'Fichiers récents',
    'search_tools':   'Rechercher des outils…',
    'no_recent':      'Aucun fichier récent',
    'ok':             'OK',
    'enter_text':     'Entrer le texte du filigrane…',
    'enter_pass':     'Entrer le mot de passe…',
    'confirm_pass':   'Confirmer le mot de passe…',
    'select_pages':   'ex: 1, 3, 5-8',
    'from_page':      'De la page',
    'to_page':        'À la page',
    'all_pages':      'Toutes les pages',
    'compress_low':   'Faible – Meilleure qualité',
    'compress_mid':   'Moyen – Équilibré',
    'compress_high':  'Élevé – Taille minimale',
    'about':          'À propos',
    'help':           'Aide & Support',
    'rate':           'Noter l\'appli',
    'share_app':      'Partager l\'appli',
    'pages':          'pages',
    'size':           'Taille',
    'author':         'Auteur',
    'created':        'Créé',
    'modified':       'Modifié',
    'tap_select':     'Appuyez ici pour sélectionner votre PDF',
    'popular':        'Populaire',
    'new_tag':        'Nouveau',
  },
  'es': {
    'app_name':       'PDF Master Pro',
    'tagline':        'La herramienta PDF definitiva',
    'get_started':    'Comenzar',
    'home':           'Inicio',
    'tools':          'Herramientas',
    'history':        'Historial',
    'settings':       'Ajustes',
    'choose_file':    'Elegir archivo PDF',
    'no_file':        'Ningún archivo seleccionado',
    'drag_drop':      'Toca para seleccionar un PDF',
    'or':             'o',
    'merge':          'Unir PDF',
    'merge_desc':     'Combinar varios PDFs en uno',
    'split':          'Dividir PDF',
    'split_desc':     'Dividir PDF en archivos separados',
    'compress':       'Comprimir PDF',
    'compress_desc':  'Reducir tamaño inteligentemente',
    'watermark':      'Marca de agua',
    'watermark_desc': 'Añadir marca de agua de texto o imagen',
    'protect':        'Proteger PDF',
    'protect_desc':   'Cifrar con contraseña',
    'unlock':         'Desbloquear PDF',
    'unlock_desc':    'Quitar protección por contraseña',
    'rotate':         'Rotar páginas',
    'rotate_desc':    'Rotar páginas libremente',
    'extract':        'Extraer texto',
    'extract_desc':   'Extraer todo el texto del PDF',
    'info':           'Info del archivo',
    'info_desc':      'Ver metadatos y detalles',
    'convert':        'Convertir PDF',
    'convert_desc':   'PDF a Word / Imágenes / Excel',
    'sign':           'Firmar PDF',
    'sign_desc':      'Añadir firma digital',
    'ocr':            'Escaneo OCR',
    'ocr_desc':       'Escanear y hacer buscable',
    'organize':       'Organizar páginas',
    'organize_desc':  'Reordenar y eliminar páginas',
    'language':       'Idioma',
    'select_lang':    'Seleccionar idioma',
    'theme':          'Tema',
    'dark':           'Modo oscuro',
    'light':          'Modo claro',
    'auto_save':      'Guardado automático',
    'notifications':  'Notificaciones',
    'privacy':        '100% Privado – archivos nunca compartidos',
    'free':           'Gratis & Ilimitado',
    'fast':           'Ultra Rápido',
    'secure':         'Seguridad bancaria',
    'version':        'Versión 1.0.0',
    'made_with':      'Hecho con ❤️ en Flutter',
    'process':        'Procesar archivo',
    'done':           '¡Listo! ✓',
    'processing':     'Procesando…',
    'cancel':         'Cancelar',
    'close':          'Cerrar',
    'success':        '¡Éxito!',
    'file_saved':     'Archivo guardado en Descargas',
    'file_processed': 'Tu archivo fue procesado exitosamente.',
    'all_tools':      'Todas las herramientas',
    'recent':         'Archivos recientes',
    'search_tools':   'Buscar herramientas…',
    'no_recent':      'No hay archivos recientes',
    'ok':             'OK',
    'enter_text':     'Ingresa el texto de marca de agua…',
    'enter_pass':     'Ingresa contraseña…',
    'confirm_pass':   'Confirmar contraseña…',
    'select_pages':   'ej: 1, 3, 5-8',
    'from_page':      'Desde página',
    'to_page':        'Hasta página',
    'all_pages':      'Todas las páginas',
    'compress_low':   'Bajo – Mejor calidad',
    'compress_mid':   'Medio – Equilibrado',
    'compress_high':  'Alto – Tamaño mínimo',
    'about':          'Acerca de',
    'help':           'Ayuda & Soporte',
    'rate':           'Valorar la app',
    'share_app':      'Compartir app',
    'pages':          'páginas',
    'size':           'Tamaño',
    'author':         'Autor',
    'created':        'Creado',
    'modified':       'Modificado',
    'tap_select':     'Toca aquí para seleccionar tu PDF',
    'popular':        'Popular',
    'new_tag':        'Nuevo',
  },
  'de': {
    'app_name':       'PDF Master Pro',
    'tagline':        'Das ultimative PDF-Werkzeug',
    'get_started':    'Loslegen',
    'home':           'Start',
    'tools':          'Werkzeuge',
    'history':        'Verlauf',
    'settings':       'Einstellungen',
    'choose_file':    'PDF-Datei wählen',
    'no_file':        'Keine Datei ausgewählt',
    'drag_drop':      'Tippen um PDF zu wählen',
    'or':             'oder',
    'merge':          'PDF zusammenführen',
    'merge_desc':     'Mehrere PDFs in einem zusammenführen',
    'split':          'PDF teilen',
    'split_desc':     'PDF in Dateien aufteilen',
    'compress':       'PDF komprimieren',
    'compress_desc':  'Dateigröße reduzieren',
    'watermark':      'Wasserzeichen',
    'watermark_desc': 'Text-Wasserzeichen hinzufügen',
    'protect':        'PDF schützen',
    'protect_desc':   'Mit Passwort verschlüsseln',
    'unlock':         'PDF entsperren',
    'unlock_desc':    'Passwortschutz entfernen',
    'rotate':         'Seiten drehen',
    'rotate_desc':    'Seiten beliebig drehen',
    'extract':        'Text extrahieren',
    'extract_desc':   'Text aus PDF extrahieren',
    'info':           'Dateiinfos',
    'info_desc':      'Metadaten anzeigen',
    'convert':        'PDF konvertieren',
    'convert_desc':   'PDF zu Word / Bilder / Excel',
    'sign':           'PDF signieren',
    'sign_desc':      'Digitale Signatur hinzufügen',
    'ocr':            'OCR-Scan',
    'ocr_desc':       'Scannen & durchsuchbar machen',
    'organize':       'Seiten organisieren',
    'organize_desc':  'Seiten neu anordnen & löschen',
    'language':       'Sprache',
    'select_lang':    'Sprache auswählen',
    'theme':          'Design',
    'dark':           'Dunkelmodus',
    'light':          'Hellmodus',
    'auto_save':      'Automatisch speichern',
    'notifications':  'Benachrichtigungen',
    'privacy':        '100% Privat – Dateien verlassen nie Ihr Gerät',
    'free':           'Kostenlos & Unbegrenzt',
    'fast':           'Blitzschnell',
    'secure':         'Bankensicherheit',
    'version':        'Version 1.0.0',
    'made_with':      'Erstellt mit ❤️ in Flutter',
    'process':        'Datei verarbeiten',
    'done':           'Fertig! ✓',
    'processing':     'Verarbeitung…',
    'cancel':         'Abbrechen',
    'close':          'Schließen',
    'success':        'Erfolg!',
    'file_saved':     'Datei in Downloads gespeichert',
    'file_processed': 'Ihre Datei wurde erfolgreich verarbeitet.',
    'all_tools':      'Alle Werkzeuge',
    'recent':         'Zuletzt geöffnet',
    'search_tools':   'Werkzeuge suchen…',
    'no_recent':      'Keine zuletzt verwendeten Dateien',
    'ok':             'OK',
    'enter_text':     'Wasserzeichen-Text eingeben…',
    'enter_pass':     'Passwort eingeben…',
    'confirm_pass':   'Passwort bestätigen…',
    'select_pages':   'z.B. 1, 3, 5-8',
    'from_page':      'Von Seite',
    'to_page':        'Bis Seite',
    'all_pages':      'Alle Seiten',
    'compress_low':   'Niedrig – Beste Qualität',
    'compress_mid':   'Mittel – Ausgeglichen',
    'compress_high':  'Hoch – Kleinste Größe',
    'about':          'Über die App',
    'help':           'Hilfe & Support',
    'rate':           'App bewerten',
    'share_app':      'App teilen',
    'pages':          'Seiten',
    'size':           'Größe',
    'author':         'Autor',
    'created':        'Erstellt',
    'modified':       'Geändert',
    'tap_select':     'Hier tippen um PDF zu wählen',
    'popular':        'Beliebt',
    'new_tag':        'Neu',
  },
};

const Map<String, String> kLanguageNames = {
  'en': '🇬🇧  English',
  'ar': '🇸🇦  العربية',
  'fr': '🇫🇷  Français',
  'es': '🇪🇸  Español',
  'de': '🇩🇪  Deutsch',
  'zh': '🇨🇳  中文',
  'tr': '🇹🇷  Türkçe',
  'pt': '🇧🇷  Português',
};

// ─────────────────────────────────────────────────────────────
//  TOOL MODEL
// ─────────────────────────────────────────────────────────────
class PdfTool {
  final String key;
  final String icon;
  final Color color;
  final bool isPopular;
  final bool isNew;

  const PdfTool({
    required this.key,
    required this.icon,
    required this.color,
    this.isPopular = false,
    this.isNew = false,
  });
}

const kTools = [
  PdfTool(key: 'merge',     icon: '🔗', color: Color(0xFF7C6FF7), isPopular: true),
  PdfTool(key: 'split',     icon: '✂️', color: Color(0xFF43E97B)),
  PdfTool(key: 'compress',  icon: '🗜️', color: Color(0xFFF7971E), isPopular: true),
  PdfTool(key: 'watermark', icon: '💧', color: Color(0xFFFF6B8A)),
  PdfTool(key: 'protect',   icon: '🔐', color: Color(0xFFA18CD1)),
  PdfTool(key: 'unlock',    icon: '🔓', color: Color(0xFF38F9D7), isNew: true),
  PdfTool(key: 'rotate',    icon: '🔄', color: Color(0xFF4FACFE)),
  PdfTool(key: 'extract',   icon: '📋', color: Color(0xFFFDA085)),
  PdfTool(key: 'info',      icon: 'ℹ️', color: Color(0xFF84FAB0)),
  PdfTool(key: 'convert',   icon: '🔁', color: Color(0xFFF093FB), isPopular: true),
  PdfTool(key: 'sign',      icon: '✍️', color: Color(0xFF43E97B), isNew: true),
  PdfTool(key: 'ocr',       icon: '🔍', color: Color(0xFFFFD700)),
  PdfTool(key: 'organize',  icon: '📑', color: Color(0xFFFF9A9E)),
];

// ─────────────────────────────────────────────────────────────
//  APP STATE
// ─────────────────────────────────────────────────────────────
class AppState extends ChangeNotifier {
  final SharedPreferences _prefs;

  AppState(this._prefs) {
    _language = _prefs.getString('language') ?? 'en';
    _isDark   = _prefs.getBool('dark_mode') ?? true;
    _autoSave = _prefs.getBool('auto_save') ?? true;
    _notifs   = _prefs.getBool('notifications') ?? true;
  }

  // ── Language ──────────────────────────────────────────────
  late String _language;
  String get language => _language;

  void setLanguage(String code) {
    _language = code;
    _prefs.setString('language', code);
    notifyListeners();
  }

  String t(String key) =>
      kTranslations[_language]?[key] ??
      kTranslations['en']?[key] ??
      key;

  bool get isRTL => _language == 'ar';

  // ── Theme ─────────────────────────────────────────────────
  late bool _isDark;
  bool get isDark => _isDark;

  void toggleTheme() {
    _isDark = !_isDark;
    _prefs.setBool('dark_mode', _isDark);
    notifyListeners();
  }

  // ── Settings ──────────────────────────────────────────────
  late bool _autoSave;
  bool get autoSave => _autoSave;
  void toggleAutoSave() {
    _autoSave = !_autoSave;
    _prefs.setBool('auto_save', _autoSave);
    notifyListeners();
  }

  late bool _notifs;
  bool get notifs => _notifs;
  void toggleNotifs() {
    _notifs = !_notifs;
    _prefs.setBool('notifications', _notifs);
    notifyListeners();
  }

  // ── Selected file ─────────────────────────────────────────
  String _selectedFile = '';
  String get selectedFile => _selectedFile;
  void setSelectedFile(String path) {
    _selectedFile = path;
    notifyListeners();
  }

  // ── Recent files (in-memory) ──────────────────────────────
  final List<String> _recent = [];
  List<String> get recent => List.unmodifiable(_recent);
  void addRecent(String path) {
    _recent.remove(path);
    _recent.insert(0, path);
    if (_recent.length > 10) _recent.removeLast();
    notifyListeners();
  }
}
